spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost/school
    password: ps123456
    driver-class-name: com.mysql.jdbc.Driver
    username: root
server:
  port: 8881
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.254.131:8761/eureka/
